# SYNTAX: python convert.py <file name>
import sys

f = ""
new_f = ""

try:
    f = open(sys.argv[1])
    new_f = open(sys.argv[1].split(".")[0] + "_new.cls", "w")
except IndexError:
    print("You have to specify filename")
    exit(1)


def fix_operators(text, operator, operator_name):
    text = text.replace(operator, operator_name)
    text = text.replace(operator_name + " ", operator_name)
    text = text.replace(" " + operator_name, operator_name)
    text = text.replace(" " + operator_name + " ", operator_name)
    text = text.replace(operator_name, " " + operator_name + " ")
    return text


body = f.read().replace("    ", "\t")
f.close()
body = body.replace("   ", "\t")
body = body.replace("//", "COMMENT_DASH_DASH")
body = body.replace("/*", "COMMENT_DASH_STAR")
body = body.replace("*/", "COMMENT_STAR_DASH")
body = fix_operators(body, ">=", "LOQ")
body = fix_operators(body, "==", "EQUAL")
body = fix_operators(body, "<=", "GOQ")
body = fix_operators(body, "!=", "NOT_EQUAL")
body = fix_operators(body, "=", "ASSIGN_VALUE")
body = fix_operators(body, "+", "ADD_VALUES")
body = fix_operators(body, "-", "SUBTRACT_VALUES")
body = fix_operators(body, "*", "MULTIPLY_VALUES")
body = fix_operators(body, "/", "DIVIDE_VALUES")
body = fix_operators(body, ":", "ARRAY_SYMBOL")
body = body.replace("> ", ">")
body = body.replace(">", "> ")
body = body.replace("> (", ">(")
body = body.replace("> >", ">>")
body = body.replace(", ", ",")
body = body.replace(",", ", ")
body = body.replace("string ", "String ")
body = body.replace("set<", "Set<")
body = body.replace("set <", "Set<")
body = body.replace("list <", "List<")
body = body.replace("list<", "List<")
body = body.replace("test", "Test")
body = body.replace("@istest", "@isTest")
body = body.replace("select", "SELECT")
body = body.replace("from", "FROM")
body = body.replace("From", "FROM")
body = body.replace("where", "WHERE")
body = body.replace("Where", "WHERE")
body = body.replace("If", "if")
body = body.replace("IF", "if")
body = body.replace("for(", "for (")
body = body.replace("if(", "if (")
body = body.replace("else{", "else {")
body = body.replace("){", ") {")
body = body.replace(")\n\t{", ") {")
body = body.replace(")\n\t\t{", ") {")
body = body.replace(")\n\t\t\t{", ") {")
body = body.replace(")\n\t\t\t\t{", ") {")
body = body.replace(")\n\t\t\t\t\t{", ") {")
body = body.replace(")\n\t\t\t\t\t\t{", ") {")
body = body.replace(")\n\t\t\t\t\t\t\t{", ") {")
body = body.replace(")\n\t\t\t\t\t\t\t\t{", ") {")
body = body.replace(")\n\t\t\t\t\t\t\t\t\t{", ") {")
body = body.replace("else\n\t{", "else {")
body = body.replace("else\n\t\t{", "else {")
body = body.replace("else\n\t\t\t{", "else {")
body = body.replace("else\n\t\t\t\t{", "else {")
body = body.replace("else\n\t\t\t\t\t{", "else {")
body = body.replace("else\n\t\t\t\t\t\t{", "else {")
body = body.replace("else\n\t\t\t\t\t\t\t{", "else {")
body = body.replace("else\n\t\t\t\t\t\t\t\t{", "else {")
body = body.replace("else\n\t\t\t\t\t\t\t\t\t{", "else {")
body = body.replace("static TestMethod", "@isTest\n\tstatic")
body = body.replace("COMMENT_DASH_DASH", "//")
body = body.replace("COMMENT_DASH_STAR", "/*")
body = body.replace("COMMENT_STAR_DASH", "*/")
body = body.replace("LOQ", ">=")
body = body.replace("EQUAL", "==")
body = body.replace("GOQ", "<=")
body = body.replace("NOT_EQUAL", "!=")
body = body.replace("ASSIGN_VALUE", "=")
body = body.replace("ADD_VALUES", "+")
body = body.replace("SUBTRACT_VALUES", "-")
body = body.replace("MULTIPLY_VALUES", "*")
body = body.replace("DIVIDE_VALUES", "/")
body = body.replace("ARRAY_SYMBOL", ":")
body = body.replace("  ", "")

new_f.write(body)
